signup/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import SignupView
from .forms import LoginForm


app_name = "signup"

urlpatterns = [
    path("signup/", SignupView.as_view(), name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="signup/login.html",
            authentication_form=LoginForm,
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

tasks/urls.py
from django.urls import path
from .views import TaskListView, TaskDetailView, TaskEditView, NewTaskView, delete_task

app_name = "tasks"

urlpatterns = [
    path("", TaskListView.as_view(), name="tasks"),
    path("new/", NewTaskView.as_view(), name="new"),
    path("task/<int:pk>/", TaskDetailView.as_view(), name="detail"),
    path("task/<int:pk>/edit/", TaskEditView.as_view(), name="edit"),
    path("task/<int:pk>/delete/", delete_task, name="delete"),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("tasks.urls")),
    path("user/", include("signup.urls")),
    path("admin/", admin.site.urls),
]

signup/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.utils import timezone
from django.contrib.auth.models import User
from django.db import models


class Task(models.Model):
    class Meta:
        ordering = ["due_date"]

    LOW_PRIORITY = "low_priority"
    HIGH_PRIORITY = "high_priority"
    STATUS_CHOICES = [
        (LOW_PRIORITY, "Low priority"),
        (HIGH_PRIORITY, "High priority"),
    ]


    user = models.ForeignKey(User, related_name="tasks", on_delete=models.CASCADE)
    title = models.TextField(max_length=50)
    text = models.TextField(max_length=200)
    created_at = models.DateTimeField(default=timezone.now)
    due_date = models.DateTimeField(blank=True, null=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=LOW_PRIORITY)

    def __str__(self):
        return str(self.title)

signup/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms

INPUT_CLASSES = "w-full py-4 px-6 rounded-xl"


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Your username",
                "class": INPUT_CLASSES,
            }
        )
    )

    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Your password",
                "class": INPUT_CLASSES,
            }
        )
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Repeat password",
                "class": INPUT_CLASSES,
            }
        )
    )


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Your username",
                "class": INPUT_CLASSES,
            }
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Your password",
                "class": INPUT_CLASSES,
            }
        )
    )

tasks/forms.py
from django import forms
from .models import Task

INPUT_CLASSES = "w-full py-4 px-6 rounded-xl"

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["title", "text", "due_date", "status"]
        widgets = {
            "title": forms.widgets.TextInput(attrs={"class":INPUT_CLASSES}),
            "text": forms.widgets.Textarea(attrs={"class":INPUT_CLASSES}),
            "due_date": forms.widgets.DateTimeInput(attrs={"class":INPUT_CLASSES}),
        }

signup/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import SignupForm


class SignupView(View):
    form_class = SignupForm
    template_name = "signup/signup.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
        return render(request, self.template_name, {"form": form})

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.utils import timezone
from datetime import timedelta

from .models import Task
from .forms import TaskForm


class TaskListView(LoginRequiredMixin, View):
    model_class = Task
    form_class = TaskForm
    template_name = "tasks/index.html"

    def get(self, request, *args, **kwargs):
        tasks = request.user.tasks.all()

        query = request.GET.get("query", "")
        filters = Task.STATUS_CHOICES
        status = request.GET.get("status", "")

        if query:
            tasks = tasks.filter(Q(title__icontains=query) | Q(text__icontains=query))

        if status:
            tasks = tasks.filter(status=status)

        overdue_tasks = tasks.filter(due_date__lte=timezone.now() - timedelta(days=1))
        today_tasks = tasks.filter(due_date__date=timezone.now())
        tomorrow_tasks = tasks.filter(due_date__date=timezone.now() + timedelta(days=1))
        week_tasks = tasks.filter(
            Q(due_date__gt=timezone.now() + timedelta(days=1))
            & Q(due_date__lte=timezone.now() + timedelta(days=7))
        )
        other_tasks = tasks.filter(due_date__gt=timezone.now() + timedelta(days=7))

        return render(
            request,
            self.template_name,
            {
                "tasks": other_tasks,
                "query": query,
                "filters": filters,
                "status": status,
                "overdue_tasks": overdue_tasks,
                "tomorrow_tasks": tomorrow_tasks,
                "week_tasks": week_tasks,
                "today_tasks": today_tasks,
            },
        )


class TaskDetailView(LoginRequiredMixin, View):
    model_class = Task
    form_class = TaskForm
    template_name = "tasks/detail.html"

    def get(self, request, pk, *args, **kwargs):
        task = get_object_or_404(self.model_class, pk=pk)
        if request.user != task.user:
            return redirect("/")
        return render(request, self.template_name, {"task": task})


class NewTaskView(LoginRequiredMixin, View):
    model_class = Task
    form_class = TaskForm
    template_name = "tasks/new.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.user = request.user
            new_task.save()
            return redirect("/")
        return render(request, self.template_name, {"form": form})


class TaskEditView(LoginRequiredMixin, View):
    model_class = Task
    form_class = TaskForm
    template_name = "tasks/edit.html"

    def get(self, request, pk, *args, **kwargs):
        task = get_object_or_404(self.model_class, pk=pk)
        if request.user != task.user:
            return redirect("/")
        form = self.form_class(instance=task)
        return render(request, self.template_name, {"form": form})

    def post(self, request, pk):
        task = get_object_or_404(self.model_class, pk=pk)
        if request.user != task.user:
            return redirect("/")
        form = self.form_class(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect("tasks:detail", pk)
        return render(request, self.template_name, {"form": form})


def delete_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if request.user != task.user:
        return redirect("/")
    task.delete()
    return redirect("/")

signup/templates/signup/login.html
{% extends 'tasks/base.html' %}

{%block title%}TApp | Login{%endblock%}

{%block content%}
<div class="w-1/2 p-6 my-6 mx-auto rounded-xl bg-gray-100"> 
    <h1 class="mb-6 text-3xl">Log In</h1>

    <form method="post" action=".">

        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>
        
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>
        
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{field.errors}}
            {% endfor %}
                {{form.non_field_errors}}
        </div>
        {% endif %}
        <div class="flex flex-row items-center justify-between mt-6">
            <button class="inline-block py-4 px-8 text-lg bg-emerald-700 hover:bg-emerald-900 rounded-xl text-white">Submit</button>
            <a href="{% url 'signup:signup' %}" class="p-3 mr-9 text-lg hover:text-emerald-500">Don't have an account yet?</a> 
        </div>
    </form>
</div>

{% endblock content %}

signup/templates/signup/signup.html
{% extends 'tasks/base.html' %}

{%block title%}TApp | Signup{%endblock%}

{%block content%}
<div class="w-1/2 p-6 my-6 mx-auto rounded-xl bg-gray-100"> 
    <h1 class="mb-6 text-3xl">Sign Up</h1>

    <form method="post" action=".">

        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>
        
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>
        
        <div class="mb-3">
            <label class="inline-block mb-2">Repeat Password</label><br>
            {{ form.password2 }}
        </div>
        
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                
                {{field.errors}}

            {% endfor %}

                {{form.non_field_errors}}
        </div>
        {% endif %}

        <button class="py-4 px-8 mt-3 text-lg bg-emerald-500 hover:bg-emerald-700 rounded-xl text-white">Submit</button>
    </form>
</div>

{% endblock content %}

tasks/templates/tasks/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <script src="https://cdn.tailwindcss.com"></script>

    <title>{%block title%}{%endblock%}</title>
</head>
<body>
    <nav class="py-2 px-6 flex justify-between items-center bg-emerald-700">
        <a href="/" class="text-2xl font-semibold text-white" >TApp</a>
        <div>
            {% if request.user.is_authenticated %}
                <form method="post" action="{% url 'signup:logout' %}" class="p-0 m-0">
                    {% csrf_token %}
                    <button class="py-2 px-3 m-0 text-lg font-semibold bg-white rounded-xl text-emerald-900 hover:bg-gray-100">
                        Log Out
                    </button>
                </form> 
            {% else %}
            <button class="py-2 px-3 m-0 text-lg font-semibold bg-white rounded-xl text-emerald-900 hover:bg-gray-100">
                <a href="{% url 'signup:login' %}" class="p-0 m-0">Log In</a>
            </button>
            {% endif %}
        </div>
    </nav>
    <div class="px-6 py-6">
        {%block content%}
        {%endblock%}
    </div>
</body>
</html>

tasks/templates/tasks/detail.html
{% extends 'tasks/base.html' %}

{% block content %}
<div class="p-6 w-1/2 mx-auto bg-gray-100 rounded-xl">
    <h1 class="text-xl font-bold">{{task.title}}</h1><br>
    <div class="mb-6">
        <p class="text-lg">{{task.text}}</p><br>
        <p class="text-lg"><span class="font-semibold">Due date:</span> {{task.due_date}}</p>
        <p class="text-lg"><span class="font-semibold">Status:</span> {{task.get_status_display}}</p>
    </div>

    <div> 
        <a href="{% url 'tasks:edit' task.pk%}" class="p-3 mr-3 bg-gray-200 hover:bg-gray-300 rounded-xl text-lg font-semibold">Edit</a>  
        <a href="{% url 'tasks:delete' task.pk %}" class="p-3 text-red-500 bg-gray-200 hover:bg-gray-300 rounded-xl text-lg font-semibold">Delete</a>
    </div>
</div>
{% endblock content %}

tasks/templates/tasks/edit.html
{% extends 'tasks/base.html' %}

{% block content %}
<div class="p-6 w-1/2 mx-auto bg-gray-100 rounded-xl">

<form method="post" action=".">
    
    {% csrf_token %}

    <div class="mb-3">
        <label class="inline-block mb-2">Task</label><br>
        {{ form.title }}
    </div>
    
    <div class="mb-3">
        <label class="inline-block mb-2">Description</label><br>
        {{ form.text }}
    </div>
    
    <div class="mb-3">
        <label class="inline-block mb-2">Due date</label><br>
        {{ form.due_date }}
    </div>
    
    <div class="mb-3">
        <label class="inline-block mb-2">Status</label><br>
        {{ form.status }}
    </div>
    
    {% if form.errors or form.non_field_errors %}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {% for field in form %}
            {{field.errors}}
        {% endfor %}
            {{form.non_field_errors}}
    </div>
    {% endif %}

    <button class="py-2 px-4 mt-1 font-semibold bg-emerald-500 hover:bg-emerald-700 rounded-xl text-white">Save</button>
</form>
</div>
{% endblock content %}

tasks/templates/tasks/index.html
{% extends 'tasks/base.html' %}

{%block title%}TApp{%endblock%}


{%block content%}
<div class="grid grid-cols-5 gap-3">

    <div class="col-span-1 rounded-xl py-6">
        <div class="mb-6">
            <a href="{% url 'tasks:new' %}" class="px-6 py-3 text-xl text-white font-semibold bg-emerald-700 hover:bg-emerald-900 rounded-xl">Add new task</a>
        </div>

        <form action="{% url 'tasks:tasks' %}" method="get">
            <div class="mb-6 border-2 rounded-xl w-full flex flex-row justify-between items-center">
                <input name="query" type="text" class="p-3 h-full w-4/5 rounded-l-xl" value="{{query}}" placeholder="">
                <button class="w-fit h-fit text-gray-400 px-3">Search</button>
            </div>
        </form>

            <p class="text-lg font-semibold">Filter by Status</p>
            <ul>
                {% for filter in filters %}
                <li class="my-3 p-3 text-lg rounded-xl {% if filter.0 == status %}bg-gray-200{% endif %}">

                    <a href="{% url 'tasks:tasks' %}?query={{query}}&status={{filter.0}}">
                    {{filter.1}}
                    </a>
                </li>
                {% endfor %}
            </ul>

        <a href="{% url 'tasks:tasks' %}" class="py-2 px-3 mt-3 text-lg text-white font-semibold rounded-xl bg-emerald-700 hover:bg-emerald-900 ">Clear</a>
    </div>

    <div class="p-6 col-span-4 rounded-xl">
        {% if overdue_tasks %}
        <h2 class="mb-6 text-xl font-semibold">Overdue</h2>
        <ul>
            {% for task in overdue_tasks %}
            <li class="mb-4 p-3 bg-white rounded-xl w-3/4">
                <div class="flex flex-row justify-between">
                    <div>
                        <a class="text-lg hover:text-emerald-800" href="{% url 'tasks:detail' task.pk %}"><span class="font-medium">{{task}}</span> - {{task.due_date}} | {{task.get_status_display}} </a> 
                    </div>
                    <div>
                        <a href="{% url 'tasks:delete' task.pk %} " class="text-red-600">Delete</a>
                        <span class="text-gray-400">| Created: {{task.created_at.date}}</span>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
        {% endif %}

        {% if today_tasks %}
        <h2 class="mb-6 text-xl font-semibold">Today</h2>
        <ul>
            {% for task in today_tasks %}
            <li class="mb-4 p-3 bg-white rounded-xl w-3/4">
                <div class="flex flex-row justify-between">
                    <div>
                        <a class="text-lg hover:text-emerald-800" href="{% url 'tasks:detail' task.pk %}"><span class="font-medium">{{task}}</span> - {{task.due_date}} | {{task.get_status_display}} </a> 
                    </div>
                    <div>
                        <a href="{% url 'tasks:delete' task.pk %} " class="text-red-600">Delete</a>
                        <span class="text-gray-400">| Created: {{task.created_at.date}}</span>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
        {% endif %}

        {% if tomorrow_tasks %}
        <h2 class="mb-6 text-xl font-semibold">Tommorow</h2>
        <ul>
            {% for task in tomorrow_tasks %}
            <li class="mb-4 p-3 bg-white rounded-xl w-3/4">
                <div class="flex flex-row justify-between">
                    <div>
                        <a class="text-lg hover:text-emerald-800" href="{% url 'tasks:detail' task.pk %}"><span class="font-medium">{{task}}</span> - {{task.due_date}} | {{task.get_status_display}} </a> 
                    </div>
                    <div>
                        <a href="{% url 'tasks:delete' task.pk %} " class="text-red-600">Delete</a>
                        <span class="text-gray-400">| Created: {{task.created_at.date}}</span>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
        {% endif %}

        {% if week_tasks %}
        <h2 class="mb-6 text-xl font-semibold">Next Week</h2>
        <ul>
            {% for task in week_tasks %}
            <li class="mb-4 p-3 bg-white rounded-xl w-3/4">
                <div class="flex flex-row justify-between">
                    <div>
                        <a class="text-lg hover:text-emerald-800" href="{% url 'tasks:detail' task.pk %}"><span class="font-medium">{{task}}</span> - {{task.due_date}} | {{task.get_status_display}} </a> 
                    </div>
                    <div>
                        <a href="{% url 'tasks:delete' task.pk %} " class="text-red-600">Delete</a>
                        <span class="text-gray-400">| Created: {{task.created_at.date}}</span>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
        {% endif %}

        <h2 class="mb-6 text-xl font-semibold">Later</h2>
        <ul>
            {% for task in tasks %}
            <li class="mb-4 p-3 bg-white rounded-xl w-3/4">
                <div class="flex flex-row justify-between">
                    <div>
                        <a class="text-lg hover:text-emerald-800" href="{% url 'tasks:detail' task.pk %}"><span class="font-medium">{{task}}</span> - {{task.due_date}} | {{task.get_status_display}} </a> 
                    </div>
                    <div>
                        <a href="{% url 'tasks:delete' task.pk %} " class="text-red-600">Delete</a>
                        <span class="text-gray-400">| Created: {{task.created_at.date}}</span>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{%endblock%}

tasks/templates/tasks/new.html
{% extends 'tasks/base.html' %}

{%block title%}New task{%endblock%}

{% block content %}
<div class="p-6 w-1/2 mx-auto bg-gray-100 rounded-xl">
    <h2 class="mb-6 mt-6 text-lg font-semibold">Add task</h2>

    <form method="post" action=".">

        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Task</label><br>
            {{ form.title }}
        </div>
        
        <div class="mb-3">
            <label class="inline-block mb-2">Description</label><br>
            {{ form.text }}
        </div>
        
        <div class="mb-3">
            <label class="inline-block mb-2">Due date</label><br>
            {{ form.due_date }}
        </div>
        
        <div class="mb-3">
            <label class="inline-block mb-2">Status</label><br>
            {{ form.status }}
        </div>
        
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{field.errors}}
            {% endfor %}
                {{form.non_field_errors}}
        </div>
        {% endif %}

        <button class="py-2 px-3 mt-3 text-lg bg-emerald-700 hover:bg-emerald-900 rounded-xl text-white">Add</button>
    </form>
</div>
{% endblock content %}